name: deploy to ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ec2-13-233-139-18
          username: linuxserver.io
          password: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: whoami
    